[package]
name = "rust-mechanical"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = { version = "0.6.2", default-features = false, features = ["termion", "date"] }
